from dataclasses import dataclass


@dataclass
class Sanitasi:
    sekolah_id: str
    semester_id: str
    sumber_air_id: str
    sumber_air_minum_id: str
    ketersediaan_air: str
    kecukupan_air: str
    minum_siswa: str
    memproses_air: str
    siswa_bawa_air: str
    toilet_siswa_laki: str
    toilet_siswa_perempuan: str
    toilet_siswa_kk: str
    toilet_siswa_kecil: str
    jml_jamban_l_g: str
    jml_jamban_l_tg: str
    jml_jamban_p_g: str
    jml_jamban_p_tg: str
    jml_jamban_lp_g: str
    jml_jamban_lp_tg: str
    tempat_cuci_tangan: str
    tempat_cuci_tangan_rusak: str
    a_sabun_air_mengalir: str
    jamban_difabel: str
    tipe_jamban: str
    a_sedia_pembalut: str
    kegiatan_cuci_tangan: str
    pembuangan_air_limbah: str
    a_kuras_septitank: str
    a_memiliki_solokan: str
    a_tempat_sampah_kelas: str
    a_tempat_sampah_tutup_p: str
    a_cermin_jamban_p: str
    a_memiliki_tps: str
    a_tps_angkut_rutin: str
    a_anggaran_sanitasi: str
    a_melibatkan_sanitasi_siswa: str
    a_kemitraan_san_daerah: str
    a_kemitraan_san_puskesmas: str
    a_kemitraan_san_swasta: str
    a_kemitraan_san_non_pem: str
    kie_guru_cuci_tangan: str
    kie_guru_haid: str
    kie_guru_perawatan_toilet: str
    kie_guru_keamanan_pangan: str
    kie_guru_minum_air: str
    kie_kelas_cuci_tangan: str
    kie_kelas_haid: str
    kie_kelas_perawatan_toilet: str
    kie_kelas_keamanan_pangan: str
    kie_kelas_minum_air: str
    kie_toilet_cuci_tangan: str
    kie_toilet_haid: str
    kie_toilet_perawatan_toilet: str
    kie_toilet_keamanan_pangan: str
    kie_toilet_minum_air: str
    kie_selasar_cuci_tangan: str
    kie_selasar_haid: str
    kie_selasar_perawatan_toilet: str
    kie_selasar_keamanan_pangan: str
    kie_selasar_minum_air: str
    kie_uks_cuci_tangan: str
    kie_uks_haid: str
    kie_uks_perawatan_toilet: str
    kie_uks_keamanan_pangan: str
    kie_uks_minum_air: str
    kie_kantin_cuci_tangan: str
    kie_kantin_haid: str
    kie_kantin_perawatan_toilet: str
    kie_kantin_keamanan_pangan: str
    kie_kantin_minum_air: str
    create_date: str
    last_update: str
    soft_delete: str
    last_sync: str
    updater_id: str
    sekolah_id_str: str
    semester_id_str: str
    sanitasi_id: str
